### ISSUE TITLE
Usage example in README

### ISSUE THREAD

**Issue by dmotte** [SixSq/mjpg-streamer-container#1]
Hi! Thanks for creating this repo :)

I would add an usage example in the README file, like this:

**docker run**:

```bash
docker run -it --rm --device /dev/video0 -p 8080:80 sixsq/mjpg-streamer \
    -i 'input_uvc.so -d /dev/video0 -r 800x480 -fps 5' \
    -o 'output_http.so -p 80'
```

docker-compose:

```yaml
version: "3"

services:
  mjpg-streamer:
    restart: always
    image: sixsq/mjpg-streamer
    devices:
      - /dev/video0
    ports:
      - 8080:80
    command: -i 'input_uvc.so -d /dev/video0 -r 800x480 -fps 5' -o 'output_http.so -p 80'
```

Then visit http://localhost:8080/?action=stream to view the MJPG stream.
